package com.moneytracker.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "taxi_exhaustions")
data class TaxiExhaustionEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val profileId: Long = 0,
    val routeId: Long = 0,
    val payMonthDate: Long, // Start epoch millis of the Pay Month this belongs to
    val date: Long, // Epoch timestamp of the trip
    val units: Int = 1,
    val farePerTrip: Double,
    val totalCost: Double = units * farePerTrip,
    val isAutoGenerated: Boolean = false, // Morning/Evening default entry
    val isCustomOutlier: Boolean = false, // e.g. Uber / Higher fare from home
    val timeOfDay: String = "MORNING", // MORNING, EVENING, CUSTOM
    val note: String = "",
    val updatedAt: Long = System.currentTimeMillis()
)
