package com.moneytracker.util

import com.moneytracker.data.local.entity.TaxiExhaustionEntity
import com.moneytracker.data.local.entity.TaxiFareEntity
import com.moneytracker.data.repository.TransactionRepository
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import java.time.DayOfWeek
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.time.temporal.TemporalAdjusters
import java.time.temporal.WeekFields
import java.util.Locale

sealed class TaxiExhaustionItemUiModel {
    data class WeeklyCollatedGroup(
        val weekNumber: Int,
        val weekLabel: String,
        val weekStartDate: Long,
        val weekEndDate: Long,
        val totalUnits: Int,
        val baseFare: Double,
        val totalCost: Double,
        val tripItems: List<TaxiExhaustionEntity>
    ) : TaxiExhaustionItemUiModel()

    data class OutlierTrip(
        val entity: TaxiExhaustionEntity
    ) : TaxiExhaustionItemUiModel()
}

object RecurringTaxiManager {

    private val taxiMutex = Mutex()
    private val weekDateFormatter = DateTimeFormatter.ofPattern("d MMM")

    /**
     * Automatic Daily Exhaustion:
     * - Executes on workdays (Monday to Friday).
     * - Logs 1 morning trip before 12:00 PM as default.
     * - Logs 1 after-hours trip after 12:00 PM as default.
     * - Does not duplicate if an entry for morning/evening already exists for the day.
     */
    suspend fun processDailyAutomaticExhaustion(repository: TransactionRepository) {
        taxiMutex.withLock {
            try {
                val now = LocalDateTime.now()
                val today = now.toLocalDate()
                val dayOfWeek = today.dayOfWeek

                // Only automate default trips on working days (Mon-Fri)
                if (dayOfWeek == DayOfWeek.SATURDAY || dayOfWeek == DayOfWeek.SUNDAY) {
                    return
                }

                val payDateDay = SettingsManager.getPayDateDay()
                val morningCutoffHour = SettingsManager.getMorningCutoffHour()
                val currentPayMonth = DateUtils.currentPayMonthLocalDate(today, payDateDay)
                val payMonthStartTs = DateUtils.toEpochMillis(currentPayMonth)
                val payMonthEndTs = DateUtils.toEpochMillis(currentPayMonth.plusMonths(1)) - 1

                val startOfDayTs = today.atStartOfDay(ZoneId.systemDefault()).toInstant().toEpochMilli()
                val endOfDayTs = today.atTime(LocalTime.MAX).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()

                val routes = repository.observeAllTaxiFares().firstOrNull() ?: emptyList()
                if (routes.isEmpty()) return

                val existingExhaustions = repository.getTaxiExhaustionsForMonth(payMonthStartTs, payMonthEndTs)

                for (route in routes) {
                    // Check / Add Morning Trip (Default entry for workday morning before cutoff hour)
                    val hasMorning = existingExhaustions.any {
                        it.routeId == route.id &&
                        it.date in startOfDayTs..endOfDayTs &&
                        it.timeOfDay.equals("MORNING", ignoreCase = true)
                    }
                    if (!hasMorning) {
                        val morningTime = today.atTime((morningCutoffHour - 4).coerceAtLeast(6), 0).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()
                        val morningEntry = TaxiExhaustionEntity(
                            profileId = repository.activeProfileId,
                            routeId = route.id,
                            payMonthDate = payMonthStartTs,
                            date = morningTime,
                            units = 1,
                            farePerTrip = route.farePerTrip,
                            totalCost = route.farePerTrip,
                            isAutoGenerated = true,
                            isCustomOutlier = false,
                            timeOfDay = "MORNING",
                            note = "Morning Trip (Default)"
                        )
                        repository.saveTaxiExhaustion(morningEntry)
                    }

                    // Check / Add Evening Trip (If current hour >= morningCutoffHour)
                    if (now.hour >= morningCutoffHour) {
                        val hasEvening = existingExhaustions.any {
                            it.routeId == route.id &&
                            it.date in startOfDayTs..endOfDayTs &&
                            it.timeOfDay.equals("EVENING", ignoreCase = true)
                        }
                        if (!hasEvening) {
                            val eveningTime = today.atTime(17, 30).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()
                            val eveningEntry = TaxiExhaustionEntity(
                                profileId = repository.activeProfileId,
                                routeId = route.id,
                                payMonthDate = payMonthStartTs,
                                date = eveningTime,
                                units = 1,
                                farePerTrip = route.farePerTrip,
                                totalCost = route.farePerTrip,
                                isAutoGenerated = true,
                                isCustomOutlier = false,
                                timeOfDay = "EVENING",
                                note = "After-Hours Trip (Default)"
                            )
                            repository.saveTaxiExhaustion(eveningEntry)
                        }
                    }
                }
            } catch (e: Exception) {
                // Fail gracefully without crashing app
            }
        }
    }

    /**
     * Collate trips for the unified monthly list:
     * - Standard base-fare trips are grouped into weekly summary rows.
     * - Outlier trips (e.g. Uber R150) are listed as distinct individual highlight models.
     */
    fun collateMonthlyExhaustions(
        exhaustions: List<TaxiExhaustionEntity>,
        route: TaxiFareEntity?
    ): List<TaxiExhaustionItemUiModel> {
        val result = mutableListOf<TaxiExhaustionItemUiModel>()
        val baseFare = route?.farePerTrip ?: 0.0

        val (outliers, standardTrips) = exhaustions.partition {
            it.isCustomOutlier || (baseFare > 0.0 && kotlin.math.abs(it.farePerTrip - baseFare) > 0.01)
        }

        // Add Outliers first / alongside
        outliers.sortedByDescending { it.date }.forEach { outlier ->
            result.add(TaxiExhaustionItemUiModel.OutlierTrip(outlier))
        }

        // Group standard trips by calendar week (Monday–Sunday)
        val weekField = WeekFields.of(Locale.getDefault())
        val groupedByWeek = standardTrips.groupBy { trip ->
            val tripDate = Instant.ofEpochMilli(trip.date).atZone(ZoneId.systemDefault()).toLocalDate()
            val weekNum = tripDate.get(weekField.weekOfWeekBasedYear())
            val year = tripDate.year
            "$year-$weekNum"
        }

        groupedByWeek.entries.sortedByDescending { it.key }.forEach { (_, tripsInWeek) ->
            if (tripsInWeek.isNotEmpty()) {
                val sampleDate = Instant.ofEpochMilli(tripsInWeek.first().date).atZone(ZoneId.systemDefault()).toLocalDate()
                val monday = sampleDate.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY))
                val sunday = sampleDate.with(TemporalAdjusters.nextOrSame(DayOfWeek.SUNDAY))

                val weekLabel = "${monday.format(weekDateFormatter)} – ${sunday.format(weekDateFormatter)}"
                val totalUnits = tripsInWeek.sumOf { it.units }
                val totalCost = tripsInWeek.sumOf { it.totalCost }
                val fareRate = if (tripsInWeek.isNotEmpty()) tripsInWeek.first().farePerTrip else baseFare

                result.add(
                    TaxiExhaustionItemUiModel.WeeklyCollatedGroup(
                        weekNumber = sampleDate.get(weekField.weekOfWeekBasedYear()),
                        weekLabel = weekLabel,
                        weekStartDate = monday.atStartOfDay(ZoneId.systemDefault()).toInstant().toEpochMilli(),
                        weekEndDate = sunday.atTime(LocalTime.MAX).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli(),
                        totalUnits = totalUnits,
                        baseFare = fareRate,
                        totalCost = totalCost,
                        tripItems = tripsInWeek.sortedByDescending { it.date }
                    )
                )
            }
        }

        return result
    }
}
